// input changes action types
export const CHANGE_CHEST_GIRTH_VALUE = 'CHANGE_CHEST_GIRTH_VALUE';
export const CHANGE_WAIST_GIRTH_VALUE = 'CHANGE_WAIST_GIRTH_VALUE';
export const CHANGE_HIP_GIRTH_VALUE = 'CHANGE_HIP_GIRTH_VALUE';
export const CHANGE_WEIGHT_VALUE = 'CHANGE_WEIGHT_VALUE';
export const CHANGE_GROWTH_VALUE = 'CHANGE_GROWTH_VALUE';
// end input changes action types

// svg action types
export const CHANGE_SVG_CHEST_GIRTH_VALUE = 'CHANGE_SVG_CHEST_GIRTH_VALUE';
export const CHANGE_SVG_WAIST_GIRTH_VALUE = 'CHANGE_SVG_WAIST_GIRTH_VALUE';
export const CHANGE_SVG_HIP_GIRTH_VALUE = 'CHANGE_SVG_HIP_GIRTH_VALUE';
export const CHANGE_SVG_WEIGHT_VALUE = 'CHANGE_SVG_WEIGHT_VALUE';
export const CHANGE_SVG_GROWTH_VALUE = 'CHANGE_SVG_GROWTH_VALUE';
// end svg action types
